import type { Metadata } from "next";
import "./globals.css";
import Header from "@/common/header/Header";
import Footer from "@/common/footer/Footer";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";

const vazirsans = localFont({
  src: [
    {
      path: "../../public/fonts/Vazir.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Vazir-Bold.woff",
      weight: "700",
      style: "nomral",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirsans.className}>
        <Toaster />
        <div className="wrapper">
          <Header />
          <h2>children</h2>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
